# Generated by Django 5.1.3 on 2024-11-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('specialization', models.CharField(choices=[('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('dermatology', 'Dermatology'), ('pediatrics', 'Pediatrics'), ('orthopedics', 'Orthopedics'), ('general', 'General Practice')], max_length=50)),
                ('biography', models.TextField(blank=True, null=True)),
                ('available_days', models.CharField(blank=True, max_length=255, null=True)),
                ('experience', models.IntegerField(default=1)),
            ],
        ),
    ]
